name: dcascade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - numpy
  - tqdm
  - matplotlib
  - spyder
  - geopandas
  - pandas=2.2.0
  - fiona=1.9.1
  - gdal=3.6.2
  - networkx=3.0
  - shapely=2.0.1

