name: Pre-Commit Checks

on:
  push:
    branches:
      #- main
      - Dcascade_v2.0
  pull_request:
    branches:
      #- main  # trigger on PRs as well
      - Dcascade_v2.0

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.3'  # Use the appropriate Python version for your project

      # Step 3: Install pre-commit
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Run pre-commit hooks on all files
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

